### ISSUE TITLE
No argument --package

### ISSUE THREAD

**Issue by nWidart** [antonioribeiro/ci#10]
This argument does not exist anymore.

```
php artisan migrate --package=pragmarx/ci
```

Also looks like the migrations aren't registered in the package, so laravel can't migrate them.

The service provider needs this:

``` php
 $this->loadMigrationsFrom(__DIR__ . '/../../migrations');
```

And then we can migrate with `php artisan migrate`

**Comment by antonioribeiro** [comment]
Version 0.9.0 was tagged, please try it.
