### ISSUE TITLE
No route to access the dashboard in readme

### ISSUE THREAD

**Issue by nWidart** [antonioribeiro/ci#11]
The readme doesn't say anything about which URI to go to.

The [routes](https://github.com/antonioribeiro/ci/blob/master/src/routes/web.php) has a bunch, none worked for me.

**Comment by antonioribeiro** [comment]
As stated [here](https://github.com/antonioribeiro/ci#installing), it should now be 

```
 http://<domain.dev>/tests-watcher/dashboard
```

**Comment by nWidart** [comment]
This was added in this commit https://github.com/antonioribeiro/ci/commit/280c0f2cc1d85ae465a8434e49b8eeed7c0ebced

Which wasn't there before.

**Comment by antonioribeiro** [comment]
Yeah, the video was a preview. Version wasn't tagged when the video was tweeted. Sorry about that. But we still have a lot to improve in the docs.

**Comment by nWidart** [comment]
I see.

Since it's an application, would be nice to have an action full project, with a docker container setup for instance. Instead of having to create the laravel project, require the package etc.

**Comment by antonioribeiro** [comment]
The starter app is here: https://github.com/antonioribeiro/tests-watcher-starter

**Comment by nWidart** [comment]
Nice. 👍 
With docker doesn't seem it'll be possible to access other files sadly.

**Comment by nWidart** [comment]
Tried to access another folder

![image](https://user-images.githubusercontent.com/882397/31319288-d7b8f8b2-ac60-11e7-811e-13d69f8c9ef4.png)

**Comment by antonioribeiro** [comment]
This directory

![image](https://user-images.githubusercontent.com/3182864/31319339-cda15d0c-ac37-11e7-96df-d9f6622c173c.png)

exists?

**Comment by antonioribeiro** [comment]
And, will you watch only your tests, not the code? Or those tests are your code?

**Comment by nWidart** [comment]
Yes, as you can see I ran `ll` on the directory path I copied, with the results.

**Comment by antonioribeiro** [comment]
Somehow `vendor/symfony/finder/Finder.php` is not being able to find that file

**Comment by antonioribeiro** [comment]
This is the command related to that error: 

```
$files = Finder::create()->files()->in($suite->testsFullPath);
```

It could be permissions, does the PHP process has permissions to read all your files?

**Comment by nWidart** [comment]
I suspect however it's because the path is not accessible from without the docker container.

**Comment by nWidart** [comment]
I can confirm it was because of docker. Had to set the project up with mamp.

It's able to show my test files now, however when running, it fails with the message `(empty)`, in the modal.

**Comment by antonioribeiro** [comment]
Had to make some changes to it, enable `script` on your phpunit tester and add the bin:

``` php
    /**
     * script
     *
     */
    'script' => '/usr/bin/script -q %s %s', // sprintf()

    /**
     * Testers
     *
     */
    'testers' => [

        'phpunit' => [
            'command' => 'vendor/bin/phpunit',
            'require_script' => true,
        ],
```

**Comment by nWidart** [comment]
Thanks.
I'm now getting:
```
script: vendor/bin/phpunit: No such file or directory
```
In the modal.

I changed the phpunit path to the one in the project:

```php
'phpunit' => [
            'command' => '/Users/nicolaswidart/Sites/Asguard/Platform/vendor/bin/phpunit',
            'require_script' => true,
        ],
```
But still same error.

(Btw it could be nice to specify a phpunit path per project.)

**Comment by antonioribeiro** [comment]
Still on docker, right?

Tester show in terminal the exact command it is executing, could you test it manually, please?

Here's an example:

![image](https://user-images.githubusercontent.com/3182864/31338230-c778f758-acd4-11e7-9e75-d614f15d5dce.png)

All paths are relative to projects, including execution

``` php
$this->shell->exec($command, $test->suite->project->path, ...

// which calls

public function exec($command, $runDir = null, Closure $callback = null, $timeout = null)
{
    $process = new Process($command, $runDir);
     ...   
}
```

That's why there's no starting slash in 

``` php
'command' => 'vendor/bin/phpunit',
```

But, yes, it could also be nice to have it by project, makes sense, thanks!

**Comment by nWidart** [comment]
No, I had to setup with MAMP as [mentionned](https://github.com/antonioribeiro/ci/issues/11#issuecomment-335026770), because inside the docker container, it had no access to local files.

This was the full output:

```
xecuting /usr/bin/script -q /private/var/folders/y7/ydfs5zlj2d92fk_1gywl_3680000gn/T/tw-Mq5tr5 vendor/bin/phpunit  /Users/nicolaswidart/Sites/Asguard/Platform/Modules/Page/Tests/PageContentIsRenderingTest.php
retrying...
retrying...
FAILED

```

**Comment by antonioribeiro** [comment]
script (`/usr/bin/script`) is installed, I presume.

works if you run it manually?:

```
/usr/bin/script -q /private/var/folders/y7/ydfs5zlj2d92fk_1gywl_3680000gn/T/tw-Mq5tr5 vendor/bin/phpunit  /Users/nicolaswidart/Sites/Asguard/Platform/Modules/Page/Tests/PageContentIsRenderingTest.php
```

**Comment by nWidart** [comment]
Hm I don't know what it is, but it exists yes. :P

Indeed, manually it runs:

![image](https://user-images.githubusercontent.com/882397/31338734-c36da1aa-ad00-11e7-8f23-64adbac6fcf4.png)

**Comment by antonioribeiro** [comment]
Please try disabling script:

```php 
'require_script' => false,
````
It will not use script (it grabs everything printed in your terminal and send to a file) anymore, but you'll have to reboot watcher and tester.

I'm pretty sure it will make no different, but that's already odd, because it's basically executing that line of code. It basically pass that command (and project path) to http://php.net/manual/en/function.proc-open.php.

**Comment by nWidart** [comment]
It indeed still fails with `script: vendor/bin/phpunit: No such file or directory`.

Full terminal output:
```
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Executing /usr/bin/script -q /private/var/folders/y7/ydfs5zlj2d92fk_1gywl_3680000gn/T/tw-N5GZ7a vendor/bin/phpunit  /Users/nicolaswidart/Sites/Asguard/Platform/Modules/Page/Tests/PageContentIsRenderingTest.php
retrying...
retrying...
FAILED
```

**Comment by antonioribeiro** [comment]
Still executing script

   Executing **/usr/bin/script** -q

**Comment by nWidart** [comment]
Yup, but it's set to false.

I'm assuming that config isn't used, since the path to phpunit isn't read from the config either.

**Comment by antonioribeiro** [comment]
It is stored in a table, but updated on Watcher boot:

![image](https://user-images.githubusercontent.com/3182864/31343302-a1a2163e-ace5-11e7-982c-70f25695a3a8.png)

So if I change it to 

![image](https://user-images.githubusercontent.com/3182864/31343331-bd8948e0-ace5-11e7-850d-b8b4984be199.png)

And reboot watcher:

````
killall php
php artisan ci:watch
````
It changes here:

![image](https://user-images.githubusercontent.com/3182864/31343394-e467ebf6-ace5-11e7-90d0-522fd78a4bbd.png)

**Comment by nWidart** [comment]
Ah I see ok.

Now erroring with 

```
PHPUnit 6.3.1 by Sebastian Bergmann and contributors.

Cannot open file "/Users/nicolaswidart/Sites/Asguard/Platform/Modules/Page/vendor/autoload.php".
```

This is normal as autoload is not in that folder.

Is it possible for this package to read the phpunit.xml file?
For example to set up the test suites: https://github.com/AsgardCms/Platform/blob/3.0/phpunit.xml#L11

**Comment by antonioribeiro** [comment]
Project must be the root of your project, everything else, if you don't add a starting slash, is (almost a must be) relative to that path.

So if your app root is 

```
/Users/nicolaswidart/Sites/Asguard
```

Your phpunit is probably at 

```
/Users/nicolaswidart/Sites/Asguard/vendor/bin/phpunit
```

So your project config could be something like this:

``` php
'Asguard' => [
    'path' => '/Users/nicolaswidart/Sites/Asguard',
    'watch_folders' => [
        'Modules/Page/App',
        'Modules/Page/Tests'
    ],
    'exclude' => [
        'Modules/Page/Tests/console/',
        'Modules/Page/Tests/screenshots/',
    ],
    'depends' => [],
    'tests_path' => 'Modules/Page/Tests',
    'suites' => [
        'unit' => [
            'tester' => 'phpunit',
            'tests_path' => '',
            'command_options' => '',
            'file_mask' => '*Test.php',
            'retries' => 0,
        ],
        'browser' => [
            'tester' => 'dusk',
            'tests_path' => 'Browser',
            'command_options' => '',
            'file_mask' => '*Test.php',
            'retries' => 0,
        ],
    ],
],
```

Of course this is just an example.

And, yes, I think it's possible to read the phpunit.xml and get some information from it.

**Comment by nWidart** [comment]
Yes, but I have more tests path. As you can see from the phpunit config file, there are multiple tests path.

**Comment by nWidart** [comment]
For now I had to duplicate the whole config section you posted, basically 1 project for each folder.

It works, tho not very easy to maintain. :D

![image](https://user-images.githubusercontent.com/882397/31353600-707497f0-ad33-11e7-944e-a7997df047b4.png)

**Comment by antonioribeiro** [comment]
Adding more suites could help you with your different tests paths:

        'Multiple suites' => [
            'path' => $basePath,
            'watch_folders' => [
                '.',
                'resources/assets/js/tests'
            ],
            'exclude' => [
                'storage',
                '.idea',
            ],
            'depends' => [],
            'tests_path' => 'tests/Multiple/',
            'suites' => [
                'module_page' => [
                    'tester' => 'phpunit',
                    'tests_path' => 'Page',
                    'command_options' => '',
                    'file_mask' => '*Test.php',
                    'retries' => 0,
                ],
                'module_media' => [
                    'tester' => 'phpunit',
                    'tests_path' => 'Media',
                    'command_options' => '',
                    'file_mask' => '*Test.php',
                    'retries' => 0,
                ],
            ],
        ],

![image](https://user-images.githubusercontent.com/3182864/31353614-8f989a34-ad09-11e7-96fd-2c06e0758b02.png)

**Comment by nWidart** [comment]
Hm interesting, I can try that.

**Comment by nWidart** [comment]
I tried this, but the watcher stops running w/o error, and dashboard has empty tests

```php
'AsgardCMS' => [
    'path' => '/Users/nicolaswidart/Sites/Asguard/Platform',
    'watch_folders' => [
        'Modules/Page',
    ],
    'tests_path' => 'tests/Something',
    'exclude' => [],
    'depends' => [],
    'suites' => [
        'page_module' => [
            'tester' => 'phpunit',
            'tests_path' => 'Modules/Page/Tests',
            'command_options' => '',
            'file_mask' => '*Test.php',
            'retries' => 0,
        ],
        'core_module' => [
            'tester' => 'phpunit',
            'tests_path' => 'Modules/Core/Tests',
            'command_options' => '',
            'file_mask' => '*Test.php',
            'retries' => 0,
        ],
    ],
],
```

**Comment by nWidart** [comment]
Oh I see, I can leave the main "tests_path" empty. 👍

**Comment by nWidart** [comment]
It might be better to have multiple projects per folder, so that only the relevant tests are re-run with the watcher.

This is my full config:

https://gist.github.com/nWidart/bc029a875ea51e36a0bbbfc372d35ce0

**Comment by antonioribeiro** [comment]
Yes, in this case it's the best option, we could add an option in the suite to not watch for files outside the suite, but I think it could be even more confusing...

**Comment by antonioribeiro** [comment]
Can we close this one already?

**Comment by nWidart** [comment]
Yes. Thanks for your help! 👍
