### ISSUE TITLE
Laravel 5: "package" method removed

### ISSUE THREAD

**Issue by twoSeats** [antonioribeiro/ci#2]
Package installs with no problem but updon trying to execute artisan after adding service provider to config/app.php produces: 

PHP Fatal error:  Call to undefined method Illuminate\Config\Repository::package() in /home/seats/code/www/rldcks/charlie/vendor/pragmarx/support/src/ServiceProvider.php on line 142
PHP Stack trace:
PHP   1. {main}() /home/seats/code/www/rldcks/charlie/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/seats/code/www/rldcks/charlie/artisan:36
PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /home/seats/code/www/rldcks/charlie/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:89
PHP   4. Illuminate\Foundation\Application->bootstrapWith() /home/seats/code/www/rldcks/charlie/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:192
PHP   5. Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap() /home/seats/code/www/rldcks/charlie/storage/framework/compiled.php:1307
PHP   6. Illuminate\Foundation\Application->registerConfiguredProviders() /home/seats/code/www/rldcks/charlie/storage/framework/compiled.php:1758
PHP   7. Illuminate\Foundation\ProviderRepository->load() /home/seats/code/www/rldcks/charlie/storage/framework/compiled.php:1404
PHP   8. Illuminate\Foundation\Application->register() /home/seats/code/www/rldcks/charlie/storage/framework/compiled.php:6344
PHP   9. PragmaRX\Ci\Vendor\Laravel\ServiceProvider->register() /home/seats/code/www/rldcks/charlie/storage/framework/compiled.php:1414
PHP  10. PragmaRX\Support\ServiceProvider->register() /home/seats/code/www/rldcks/charlie/vendor/pragmarx/ci/src/Vendor/Laravel/ServiceProvider.php:49
PHP  11. PragmaRX\Support\ServiceProvider->preRegister() /home/seats/code/www/rldcks/charlie/vendor/pragmarx/support/src/ServiceProvider.php:116
PHP  12. PragmaRX\Support\ServiceProvider->registerConfig() /home/seats/code/www/rldcks/charlie/vendor/pragmarx/support/src/ServiceProvider.php:101
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Config\Repository::package()' in /home/seats/code/www/rldcks/charlie/vendor/pragmarx/support/src/ServiceProvider.php:142
Stack trace:
#0 /home/seats/code/www/rldcks/charlie/storage/framework/compiled.php(1721): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}

**Comment by antonioribeiro** [comment]
Yeah, Laravel 5 was launched yesterday, this package is not ready for it, yet.

**Comment by antonioribeiro** [comment]
But feel free to PR a change to make it work on L5, should not be too hard. ;)
