### ISSUE TITLE
environment variable not set pusher key

### ISSUE THREAD

**Issue by tuanmy** [antonioribeiro/ci#4]
Hi Antonio
I have a problem when I try installing antonioribeiro/ci package. 
And the error "environment variable not set: PUSHER_KEY" appear at step "Create a database, configure on your Laravel app and migrate it" when i run "php artisan migrate --package=pragmarx/ci" 
I have looked for on Google and still do not know the reason why ? 
Please help me fix this problem!
Thank a lot ! :)
https://gyazo.com/8b3374b01c21ffcd4eeb9da0af5e9663

**Comment by holdenrehg** [comment]
I'm having this same issue. Has this been resolved?

**Comment by holdenrehg** [comment]
A quick fix for this is to comment out or set defaults in the config files where these environment variables are referenced. `PUSHER_KEY` is used in `config/broadcasting.php`

**Comment by antonioribeiro** [comment]
This was related to another package. Already fixed. Please check the latest version, lots of new stuff.
