### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by robsontenorio** [antonioribeiro/ci#43]
Hi,

It does not handle path with "spaces".

```
'myproject' => [
            'path'          => '/Volumes/Backup\ HD/Dropbox/dev/myproject',
...
```

![captura de tela 2017-10-28 as 02 03 57](https://user-images.githubusercontent.com/118955/32131093-6100ba92-bb84-11e7-8aa7-61e4e6a24c90.png)

**Comment by robsontenorio** [comment]
@antonioribeiro any workarounds?

**Comment by antonioribeiro** [comment]
Should not be a problem, no need to scape it. 

Works fine here:

![image](https://user-images.githubusercontent.com/3182864/32637094-fa8d12e0-c59e-11e7-8934-190d79a947f2.png)


![image](https://user-images.githubusercontent.com/3182864/32637126-2fdf8bda-c59f-11e7-85f6-3609127380ba.png)

**Comment by robsontenorio** [comment]
Well, maybe a OSX issue. I solved moving my workspace to another folder. thanks!

**Comment by antonioribeiro** [comment]
Also on OSX here.

**Comment by antonioribeiro** [comment]
No need to move it, just try to symlink your /dev, like

``` bash
ln -s /Volumes/Backup\ HD/Dropbox/dev /dev
```

**Comment by robsontenorio** [comment]
@antonioribeiro  Sem problemas, parabéns pelo projeto :)
