### ISSUE TITLE
Installation steps not correct

### ISSUE THREAD

**Issue by nWidart** [antonioribeiro/ci#8]
Hello,

I'm following the installation steps, however, the service provider mentioned isn't correct.

```php
'PragmaRX\TestsWatcher\Vendor\Laravel\ServiceProvider',
```

Seems like the correct one is:
```php
\PragmaRX\Ci\Vendor\Laravel\ServiceProvider::class,
```

This doesn't exist.

**Comment by antonioribeiro** [comment]
Yeah, when you tried it version was still not tagged. Tagged version 0.9.0, and all should work now. Docs updated.
If you are using Laravel 5.5, no need to configure the service provider, it's auto-discovered.
